# Setup
title:               나쯔블로그
tagline:             나쯔나쯔
description:         '나쯔나쯔나쯔.'
url:                 https://mp662002.github.io
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              mp662002
  url:               https://blog.naver.com/mp662002
  email:             mp662002@naver.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
